
/*funcoes de LATEX*/
void initHTML (FILE * html_file);
char * tituloH(char * titulo);
char * autoresH(char * autores);
char * newpageH();
char * paragrafoH();
char * listafigH();
char * tableconH();
char * italicoH(char * texto);
char * negritoH(char * texto);
char * sublinhadoH(char * texto);
char * nisH(char * texto);
char * sectionH(char * texto,char nivel);
char * fimH();
char * legendaH(char * texto);
char * tabelaH(char * texto);
char * tabelalinhaH(char * texto);
char * fimtabelaH();
char * itemH(char * texto);
char * loH();
char * liH();
char * corH(char * texto);
char * fimimagemH();
char * imagemH(char * texto);
char * tabH();
char * itemDH(char * texto);
char * citacaoH(char * texto);
char * dicH();
char * tabH();
char * hlinkH(char * texto);
char * dotsH();
char * initResumoH();