
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[231] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   35,   33,   33,   34,   33,   33,
       30,   33,   33,   34,   33,   33,   33,   33,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   28,    0,    0,    0,    0,    0,   15,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   12,    0,    0,    0,    0,    0,    0,   11,    0,

        0,    0,   13,    0,    0,    0,    0,    0,   17,    0,
       15,    0,    0,   10,   31,   32,    0,    0,    0,    0,
        0,    0,    0,   12,    0,    0,    9,    8,    6,    5,
       11,    0,    0,    0,   13,    0,    0,    0,    0,    0,
        0,    1,    0,   31,   32,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    9,    8,    6,    5,    0,   14,
        0,    0,    0,    0,    0,    0,   16,    0,    0,    0,
       24,   19,    0,    0,    0,    0,    7,   25,   14,    0,
        0,    0,    0,    0,    0,    0,    0,   24,    0,    0,
       18,    0,    7,   25,    0,    4,    0,    0,    0,    0,

        0,    0,    0,    0,   21,    0,    0,    0,    0,    0,
       27,   29,    0,    0,    0,    0,    0,    0,    2,   29,
        0,    3,    0,   23,    0,   26,   20,   23,   22,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    6,    6,
        6,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    7,    1,    1,    1,    1,
        1,    1,    1,    8,    1,    1,    1,    9,    1,    1,
       10,   11,   12,   13,    1,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,    1,   30,   31,   32,   33,   34,    1,    1,
        1,   35,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[36] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[251] =
    {   0,
        0,    2,   12,   14,   24,   26,   36,   38,   48,   50,
       60,   62,   72,   74,   84,   86,   96,   98,  108,  110,
      120,  122,  132,  134,  144,  146,  156,  158,  168,  170,
      180,  182,  192,  194,  379,  380,  364,  380,  363,  188,
      380,  216,  247,  357,  198,  179,  187,  240,  360,  366,
      362,  350,  353,  345,    9,  201,  355,   14,  343,  189,
       23,   38,  238,  339,  262,   10,  348,  196,   50,  354,
      231,   59,  380,   71,    0,  350,  361,  344,    0,  335,
      340,  348,  347,  346,  342,  323,  321,  321,  326,  323,
      328,    0,  332,  330,  336,  335,  334,  333,    0,  333,

      311,  310,    0,  324,  324,  306,  307,  309,  380,  326,
        0,  323,  315,  380,    0,    0,  302,  303,  305,  315,
       91,  296,  300,    0,  304,  299,    0,    0,    0,    0,
        0,  311,  301,  297,    0,  304,  291,  274,  228,  285,
      303,  380,  277,    0,    0,  285,  272,  290,  289,  280,
      270,  272,  279,  283,    0,    0,    0,    0,  282,    0,
      281,  266,  265,  268,  264,  265,  380,  259,  237,  240,
        0,  380,  239,  224,  229,  214,    0,  216,    0,  223,
      210,  184,  183,  187,  176,  160,  155,    0,  166,  146,
      380,  253,    0,  164,  171,  380,  279,  157,  145,  153,

      151,  145,  125,  134,  380,  124,  283,  141,  114,  129,
      380,    0,  135,  118,  119,  108,  115,  117,  380,    0,
      115,  380,  105,    0,  103,  380,  380,    0,  380,  380,
      313,  105,  103,   93,   91,   81,   67,   57,   53,   45,
       19,   11,    9,    7,  315,  317,  319,    5,  321,    0
    } ;

static yyconst flex_int16_t yy_def[251] =
    {   0,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,   43,   43,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  232,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  233,  230,  230,  230,  230,  230,  230,  234,  230,

      230,  230,  235,  230,  230,  230,  230,  230,  230,  230,
      232,  230,  230,  230,  236,  237,  230,  230,  230,  230,
      230,  230,  230,  233,  230,  230,  238,  239,  240,  241,
      234,  230,  230,  230,  235,  230,  230,  230,  230,  230,
      230,  230,  230,  236,  237,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  238,  239,  240,  241,  230,  242,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      243,  230,  230,  230,  230,  230,  244,  230,  242,  245,
      230,  230,  230,  230,  230,  230,  230,  243,  230,  230,
      230,  230,  244,  230,  245,  230,  230,  230,  230,  246,

      230,  230,  230,  230,  230,  230,  230,  247,  230,  246,
      230,  248,  249,  230,  230,  230,  230,  247,  230,  248,
      249,  230,  230,  250,  230,  230,  230,  250,  230,    0,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230
    } ;

static yyconst flex_int16_t yy_nxt[416] =
    {   0,
      228,   37,   38,   37,   38,  220,   39,  193,   39,  188,
       40,  179,   40,   37,   41,   37,   41,   81,   39,  158,
       39,  108,   42,  105,   42,   37,   41,   37,   41,   83,
       39,  106,   39,   84,   43,   89,   43,   37,   41,   37,
       41,   90,   39,   95,   39,  157,   43,   96,   43,   37,
       41,   37,   41,  156,   39,   81,   39,  155,   43,   97,
       43,   37,   44,   37,   44,   98,   39,  145,   39,  103,
       40,   80,   40,   37,   41,   37,   41,   90,   39,   83,
       39,  144,   45,   84,   45,   37,   41,   37,   41,  100,
       39,  135,   39,  131,   43,   82,   43,   37,   41,   37,

       41,  142,   39,  124,   39,  111,   46,  150,   46,   37,
       41,   37,   41,  229,   39,  227,   39,  222,   40,  219,
       40,   37,   41,   37,   41,  226,   39,  225,   39,  224,
       47,  223,   47,   37,   41,   37,   41,  222,   39,  211,
       39,  148,   40,  219,   40,   37,   41,   37,   41,  216,
       39,  215,   39,  214,   40,  213,   40,   37,   41,   37,
       41,  212,   39,  211,   39,  209,   48,  208,   48,   37,
       41,   37,   41,  196,   39,  194,   39,  204,   40,  203,
       40,   37,   41,   37,   41,  202,   39,  148,   39,  201,
       40,   51,   40,   37,   41,   37,   41,  200,   39,   92,

       39,   51,   40,   75,   40,   63,   52,  199,  230,  230,
       76,  198,   53,   54,   54,   93,   52,   55,   55,   51,
       94,   85,   53,  197,   74,  196,   85,  194,   55,   56,
       87,  192,   57,   86,   58,   87,   59,   60,   61,  191,
       62,   99,   63,   51,  164,   64,   65,   66,   99,   67,
       51,  190,  101,  165,  189,   82,  100,  187,   52,  101,
       68,  186,   82,  205,   75,   69,   54,   59,   70,   61,
       55,   53,  103,   71,  206,  185,   64,   72,  184,  104,
       67,  183,   83,  207,  207,  148,   84,  207,  207,  182,
      181,  180,  178,  177,  176,  175,  174,  173,  217,  172,

      171,  170,  169,  168,  167,  166,  163,  217,  162,  161,
      148,  160,  217,   36,   36,  195,  195,  210,  210,  218,
      218,  221,  221,  159,  154,  153,  152,  151,  149,  148,
      147,  146,  143,  142,  141,  140,  139,  138,  137,  136,
      134,  133,  132,  130,  129,  128,  127,  126,  125,  123,
      122,  121,  120,  119,  118,  117,  116,  115,  114,  113,
      112,  110,  109,  105,   92,  107,  102,   91,   88,   82,
       81,   80,   79,   78,   77,   73,   50,   49,  230,   35,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,

      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230
    } ;

static yyconst flex_int16_t yy_chk[416] =
    {   0,
      250,    1,    1,    2,    2,  248,    1,  244,    2,  243,
        1,  242,    2,    3,    3,    4,    4,   75,    3,  241,
        4,   75,    3,   66,    4,    5,    5,    6,    6,   55,
        5,   66,    6,   55,    5,   58,    6,    7,    7,    8,
        8,   58,    7,   61,    8,  240,    7,   61,    8,    9,
        9,   10,   10,  239,    9,   62,   10,  238,    9,   62,
       10,   11,   11,   12,   12,   62,   11,  237,   12,   72,
       11,   69,   12,   13,   13,   14,   14,   69,   13,   72,
       14,  236,   13,   72,   14,   15,   15,   16,   16,   74,
       15,  235,   16,  234,   15,   74,   16,   17,   17,   18,

       18,  121,   17,  233,   18,  232,   17,  121,   18,   19,
       19,   20,   20,  225,   19,  223,   20,  221,   19,  218,
       20,   21,   21,   22,   22,  217,   21,  216,   22,  215,
       21,  214,   22,   23,   23,   24,   24,  213,   23,  210,
       24,  209,   23,  208,   24,   25,   25,   26,   26,  206,
       25,  204,   26,  203,   25,  202,   26,   27,   27,   28,
       28,  201,   27,  200,   28,  199,   27,  198,   28,   29,
       29,   30,   30,  195,   29,  194,   30,  190,   29,  189,
       30,   31,   31,   32,   32,  187,   31,  186,   32,  185,
       31,   40,   32,   33,   33,   34,   34,  184,   33,   60,

       34,   45,   33,   46,   34,   46,   40,  183,   47,   47,
       46,  182,   40,   47,   40,   60,   45,   47,   40,   42,
       60,   68,   45,  181,   45,  180,   56,  178,   45,   42,
       68,  176,   42,   56,   42,   56,   42,   42,   42,  175,
       42,   71,   42,   48,  139,   42,   42,   42,   63,   42,
       43,  174,   71,  139,  173,   71,   63,  170,   48,   63,
       43,  169,   63,  192,   48,   43,   48,   43,   43,   43,
       48,   43,   65,   43,  192,  168,   43,   43,  166,   65,
       43,  165,   65,  197,  197,  164,   65,  207,  207,  163,
      162,  161,  159,  154,  153,  152,  151,  150,  207,  149,

      148,  147,  146,  143,  141,  140,  138,  207,  137,  136,
      134,  133,  207,  231,  231,  245,  245,  246,  246,  247,
      247,  249,  249,  132,  126,  125,  123,  122,  120,  119,
      118,  117,  113,  112,  110,  108,  107,  106,  105,  104,
      102,  101,  100,   98,   97,   96,   95,   94,   93,   91,
       90,   89,   88,   87,   86,   85,   84,   83,   82,   81,
       80,   78,   77,   76,   70,   67,   64,   59,   57,   54,
       53,   52,   51,   50,   49,   44,   39,   37,   35,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,

      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "luthor.l"
#line 2 "luthor.l"
#include <unistd.h>
#include <fcntl.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#define KGRN  "\x1B[32m"
#define KNRM  "\x1B[0m"


/*stack que guarda os estados*/
int estado=1;
int ultimoEstado;
int estados[100];
int apontaEstados=0;

/*modo que o utilizador pretende compilar*/
int _modoHTML=0;
int _modoLatex=0;
int _modoEcran=0;
int _versionORhelp=0;

/*files a serem criados*/
FILE *html_file=NULL;
FILE *latex_file=NULL;

void printa(char * formato,char * texto);

/*definicao de todos os estados possiveis*/
/*   1      2       3         4          5        6       7     8       9     10     11    12  13    14   15     16   */

#line 650 "lex.yy.c"

#define INITIAL 0
#define NORMAL 1
#define NEGRITO 2
#define ITALICO 3
#define SUBLINHADO 4
#define COMENTARIO 5
#define VERBATIM 6
#define LISTA 7
#define TABELA 8
#define IMAGEM 9
#define NIS 10
#define FOOTNOTE 11
#define COR 12
#define LINHA 13
#define LATEX 14
#define HTML 15
#define LEGENDA 16

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 36 "luthor.l"

	/* fim de tabs */
#line 851 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 231 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 380 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 38 "luthor.l"
{ultimoEstado = estados[apontaEstados];
																		     if(apontaEstados>0) apontaEstados--;
																				//printf("...%d..",estados[apontaEstados]);
																			 switch(ultimoEstado)
																			 {
																			 	case 2: 
																			 	printa("%s","}");
																				break;
																			 	case 3:
																			 	printa("%s","}");
																			 	break;
																			 	case 4:
																			 	printa("%s","}");
																			 	break;
																			 	case 5:
																			 	printa("%s","\\end{comment}\n");
																			 	break;
																			 	case 6://verbatim
																			 	printa("%s","}");																			 	break;
																			 	case 7:
																			 	printa("%s","</lista>");
																			 	break;
																			 	case 8:
																			 	printa("%s",(char*)fimtabelaL());
																			 	break;
																			 	case 9:
																			 	printa("%s","</img>");
																			 	break;
																			 	case 10:
																			 	printa("%s","}}}");
																			 	break;
																			 	case 11:
																			 	printa("%s","}");//footnote>
																			 	break;
																			 	case 12://cor
																			 	printa("%s","}");
																			 	break;
																				case 16:
																			 	printa("%s","}");
																			 	break;
																			 	default:
																			 	break;
																			 }
																			 
										 									 ultimoEstado= estados[apontaEstados];
																			 BEGIN ultimoEstado;
																			}
	YY_BREAK
/*titulo*/
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 87 "luthor.l"
printa("%s",(char*)tituloL(tira_ns(yytext+8)));
	YY_BREAK
/*autores*/
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 90 "luthor.l"
printa("%s",(char*)autoresL(tira_ns(yytext+9)));
	YY_BREAK
/*nivel de seccao (pode ser 1, 2 ou 3)*/
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 93 "luthor.l"
printa("%s",(char*)sectionL(tira_ns(yytext+6),yytext[4]));
	YY_BREAK
/*lista ordenada*/
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 96 "luthor.l"
printa("%s\n",(char*)yytext+4);
	YY_BREAK
/*lista nao ordenada*/
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 99 "luthor.l"
printa("%s\n",(char*)yytext+4);
	YY_BREAK
/*novo item*/
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 102 "luthor.l"
printa("%s\n",(char*)yytext+4);
	YY_BREAK
/*apenas no LaTeX*/
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 105 "luthor.l"
printa("<justL>%s",(char*)yytext+4);
	YY_BREAK
/*apenas no HTML*/
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 108 "luthor.l"
printa("<justH>%s",(char*)yytext+4);
	YY_BREAK
/*quebra de linha*/
case 10:
YY_RULE_SETUP
#line 111 "luthor.l"
printa("%s",(char*)paragrafoL());
	YY_BREAK
/*negrito*/
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 114 "luthor.l"
{BEGIN NEGRITO;
																			 estado=NEGRITO;
																			 apontaEstados++;
																			 estados[apontaEstados]=estado;
																	 		 printa("%s",(char*)negritoL(yytext+3));
																	 		}
	YY_BREAK
/*italico*/
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 122 "luthor.l"
{BEGIN ITALICO;
																			 estado=ITALICO;
																			 apontaEstados++;
																			 estados[apontaEstados]=estado;
																	 		 printa("%s",(char*)italicoL(yytext+3));
																	 		}
	YY_BREAK
/*sublinhado*/
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 130 "luthor.l"
{BEGIN SUBLINHADO;
																			 estado=SUBLINHADO;
																			 apontaEstados++;
																			 estados[apontaEstados]=estado;
																	 		 printa("%s",(char*)sublinhadoL(yytext+3));
																	 		}
	YY_BREAK
/*combinaÃ§Ã£o de negrito, italico e sublinhado*/
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 138 "luthor.l"
{BEGIN NIS;
																			 estado=NIS;
																			 apontaEstados++;
																			 estados[apontaEstados]=estado;
																	 		 if(_modoLatex) printa("%s",(char*)nisL(yytext+5));
																	 		 //if(_modoHTML) nisH(yytext+5);
																	 		 if(_modoEcran) printf("nis{%s}\n", yytext+5);
																	 		}
	YY_BREAK
/*comentario*/
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 148 "luthor.l"
{BEGIN COMENTARIO;
																			 estado=COMENTARIO;
																			 apontaEstados++;
																			 estados[apontaEstados]=estado;
																	 		 printa("\\begin{comment}%s",(char*)yytext+3);
																	 		}
	YY_BREAK
/*simbolo do latex*/
case 16:
YY_RULE_SETUP
#line 156 "luthor.l"
printa("%s","\\LaTeX");
	YY_BREAK
/*tab*/
case 17:
YY_RULE_SETUP
#line 159 "luthor.l"
printa("%s","\\vspace{10 mm}");
	YY_BREAK
/*link*/
case 18:
YY_RULE_SETUP
#line 162 "luthor.l"
printa("%s","\\link");
	YY_BREAK
/*data do dia*/
case 19:
YY_RULE_SETUP
#line 165 "luthor.l"
printa("%s","\\today");
	YY_BREAK
/*fim de capa*/
case 20:
YY_RULE_SETUP
#line 168 "luthor.l"
{printa("%s",(char*)fimdecapaL());
																			 printa("%s",(char*)newpageL());
																			}
	YY_BREAK
/*indice*/
case 21:
YY_RULE_SETUP
#line 172 "luthor.l"
printa("%s","\\tableofcontents\n");
	YY_BREAK
/*indice de imagens*/
case 22:
YY_RULE_SETUP
#line 175 "luthor.l"
printa("%s","\\listoffigures\n");
	YY_BREAK
/*nota de rodape*/
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 179 "luthor.l"
{BEGIN FOOTNOTE;
																			 estado=FOOTNOTE;
																			 apontaEstados++;
																			 estados[apontaEstados]=estado;
																	 		 printa("\\footnote{%s",(char*)yytext+10);
																	 		}
	YY_BREAK
/*cores do texto*/
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 186 "luthor.l"
{BEGIN COR;
																									 	 estado=COR;
																									 	 apontaEstados++;
																									 	 estados[apontaEstados]=estado;
																							 		 	 printa("\\textcolor{red}{%s",(char*)yytext+10);
																							 			}
	YY_BREAK
/*texto nao formatado*/
case 25:
YY_RULE_SETUP
#line 194 "luthor.l"
{BEGIN VERBATIM;
																		 	 estado=VERBATIM;
																		 	 apontaEstados++;
																		 	 estados[apontaEstados]=estado;
																 		 	 printa("\\begin{verbatim}%s",(char*)yytext+4);
																 			}
	YY_BREAK
/*comeÃ§ar tabela tabela*/
case 26:
YY_RULE_SETUP
#line 202 "luthor.l"
{BEGIN TABELA;
																			 estado=TABELA;
																			 apontaEstados++;
																			 estados[apontaEstados]=estado;
																			 printa("%s",(char*)tabelaL(yytext+7));
																			}
	YY_BREAK
/*inserir linha da tabela*/
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 210 "luthor.l"
{BEGIN LINHA;
																			 estado=LINHA;
																			 apontaEstados++;
																			 estados[apontaEstados]=estado;
																			 printa("%s",(char*)tabelalinhaL(yytext+7));
																			 //printf("....");
																			}																											
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 218 "luthor.l"
printa("%s",yytext);
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 219 "luthor.l"
{BEGIN LEGENDA;
																			 estado=LEGENDA;
																			 apontaEstados++;
																			 estados[apontaEstados]=estado;
																			 printa("%s",(char*)legendaL(yytext+9));
																			}
	YY_BREAK
/*omissao da quebra*/
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 227 "luthor.l"
;
	YY_BREAK
/*aparece apenas no HTML*/
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 230 "luthor.l"
{BEGIN HTML;
																		 estado=HTML;
																		 apontaEstados++;
																		 estados[apontaEstados]=estado;
																		 printa("<linha>%s",yytext+7);
																		}	
	YY_BREAK
/*aparece apenas no LaTeX*/
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 237 "luthor.l"
{BEGIN LATEX;
																		 estado=LATEX;
																		 apontaEstados++;
																		 estados[apontaEstados]=estado;
																		 printa("<linha>%s",yytext+7);
																		}	
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 244 "luthor.l"
printa("%s",yytext);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 245 "luthor.l"
ECHO;
	YY_BREAK
#line 1270 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NORMAL):
case YY_STATE_EOF(NEGRITO):
case YY_STATE_EOF(ITALICO):
case YY_STATE_EOF(SUBLINHADO):
case YY_STATE_EOF(COMENTARIO):
case YY_STATE_EOF(VERBATIM):
case YY_STATE_EOF(LISTA):
case YY_STATE_EOF(TABELA):
case YY_STATE_EOF(IMAGEM):
case YY_STATE_EOF(NIS):
case YY_STATE_EOF(FOOTNOTE):
case YY_STATE_EOF(COR):
case YY_STATE_EOF(LINHA):
case YY_STATE_EOF(LATEX):
case YY_STATE_EOF(HTML):
case YY_STATE_EOF(LEGENDA):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 231 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 231 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 230);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 245 "luthor.l"






/*


int main(int argc, char* argv[]){
	
//iniciar o lex no estado 1, estado NORMAL
estados[0]=1;
BEGIN NORMAL;
	
//Reconhecedor dos padroes suportados
	if(argc<2 || argc >4 || argc==3){
		printf("PadrÃ£o desconhecido:\n\nArgumentos vÃ¡lidos:\n");
		printf(" lexLuthor -l -o nome\n");
		printf(" lexLuthor -h -o nome\n");
		printf(" lexLuthor -l\n");
		printf(" lexLuthor -h\n");
		printf(" lexLuthor -lh -o nome\n");
		printf(" lexLuthor -hl -o nome\n");
		printf(" lexLuthor -lh\n");
		printf(" lexLuthor -hl\n");
	} else {
		if(argc==4){//tem 4 args ou seja tem output
		
			if(strcmp(argv[2],"-o"))
				{
					printf("Terceiro parÃ¢metro nÃ£o Ã© -o\n");
					return -1;
				}
			char * nome1 = strdup(argv[3]);
			char * nome2 = strdup(argv[3]);
			char * fileout1=strdup(strcat(nome1,".tex"));
			char * fileout2=strdup(strcat(nome2,".html"));
			
			if(!strcmp(argv[1],"-l"))
			{
				_modoLatex=1;
				latex_file = fopen(fileout1, "w+");
				if(latex_file < 0)    return 1;
				
				initLaTeX();
				
				
			} else if(!strcmp(argv[1],"-h"))
			{
				_modoHTML=1;
				html_file = fopen(fileout2, "w+");
				if(html_file < 0)    return 1;
				
				//initHTML();
				
			} else if(!strcmp(argv[1],"-lh"))
			{
				_modoHTML=1;
				_modoLatex=1;
				latex_file = fopen(fileout1, "w+");
				html_file = fopen(fileout2, "w+");
			
			
				if(latex_file < 0 || html_file < 0)    return 1;
				
				initLaTeX();
				//initHTML();
				
			}
			
//			if(dup2(file,1) < 0)    return 1;
		}


		else return -1;//nao Ã© vÃ¡lido -l ou -h

//execucao do lex
		yylex();


		if(_modoLatex && !_modoEcran)
			fprintf(latex_file,"%s",fimL());
		if(_modoHTML && !_modoEcran)
			fprintf(html_file,"%s",fimL());
		if(_modoEcran){
			if(_modoLatex)
				fprintf(latex_file,"%s",fimL());
			else if(_modoHTML)
				fprintf(html_file,"%s",fimL());

		}
	}

	return 0;
}



*/



void printa(char * formato,char * texto){
	
	if(_modoHTML==1)
		fprintf(html_file,formato,texto);
			
	if(_modoLatex==1)
		fprintf(latex_file,formato,texto);
			
}



int main(int argc, char* argv[]){
	
	/*iniciar o lex no estado 1, estado NORMAL*/	
estados[0]=1;
BEGIN NORMAL;
	
	/*Reconhecedor dos padroes suportados*/

	_versionORhelp=verificaArgs_callHelp(argc, argv);
	_versionORhelp=verificaArgs_callVersion(argc, argv);
	if (verificaArgs_ArgumentosOut(argc, argv)) {
		if(argc==4){ /*tem 4 args ou seja tem output*/
		
			if(strcmp(argv[2],"-o"))
				{
					printf("Terceiro parÃƒÂ¢metro nao ÃƒÂ© -o\n");
					return -1;
				}
		}
		
		char * nome1 = strdup(argv[3]);
		char * nome2 = strdup(argv[3]);
		char * fileout1=strdup(strcat(nome1,".tex"));
		char * fileout2=strdup(strcat(nome2,".html"));

		if(strcmp(argv[1],"-h")==0)
		{
			_modoHTML=1;
			html_file = fopen(fileout2, "w+");
			if(html_file < 0)    return 1;
			
			//initHTML();
		}

		else if(strcmp(argv[1],"-l")==0){
			_modoLatex=1;
			latex_file = fopen(fileout1, "w+");
			if(latex_file < 0)    return 1;
			
			initLaTeX(latex_file);
		}
		else if(strcmp(argv[1],"-lh")==0 || strcmp(argv[1],"-hl")==0){
			_modoHTML=1;
			_modoLatex=1;
			latex_file = fopen(fileout1, "w+");
			html_file = fopen(fileout2, "w+");
		}

	/*execucao do lex*/
		if(_modoLatex || _modoHTML || _modoEcran)
			yylex();


/*so coloca estiver em modo de latex*/
		if(_modoLatex && !_modoEcran)
			fprintf(latex_file,"%s",(char*)fimL());
		if(_modoHTML && !_modoEcran)
			;//fprintf(html_file,"%s",fimH());
		if(_modoEcran){
			if(_modoLatex)
				printf("%s",(char *)fimL());
				
			else if(_modoHTML==1)
				;//printf("%s",fimH());
				
		}
	
	} 

	if (_modoHTML==0 && _modoLatex==0 && _modoEcran==0 && _versionORhelp==0){
		printf("ERROR - maybe you need to use:\n");
		printf("--h or --help [all options and description]\n");
	} 
	return 0;
}



	/*Verifica se a invocacao ocorreu com argumentos de help*/
int verificaArgs_callHelp(int argc, char* argv[]){
	int res = 0;
	if (argc==2 && (strcmp(argv[1],"--h")==0 || strcmp(argv[1],"--help")==0)){
		printf("\t lexLuthor -l -o [nome]\n");
		printf("\t lexLuthor -h -o [nome]\n");
		printf("\t lexLuthor -l\n");
		printf("\t lexLuthor -h\n");
		printf("\t lexLuthor -lh -o [nome]\n");
		printf("\t lexLuthor -hl -o [nome]\n");
		printf("\t lexLuthor -lh\n");
		printf("\t lexLuthor -hl\n");
		printf("\n\n");
		printf("\t\t --v or --version [version of LexLuthor]\n");
		printf("\t\t -l [only creats LaTeX output]\n");
		printf("\t\t -h [only creats HTML output]\n");
		printf("\t\t -o [to chose the output name]\n");
		res=1;
	}
	return res;
}

	/*Verifica se a invocacao ocorreu com argumentos de versao*/
int verificaArgs_callVersion(int argc, char* argv[]){
	int res = 0;
	if (argc==2 && (strcmp(argv[1],"--v")==0 || strcmp(argv[1],"--version")==0)){
		printf("FlexLuthor version 3.2");
		printf(KGRN " Kryptonite");
		printf(KNRM "\nCreated by Duarte Duarte and Fabio Gomes\nProduct from BananaCorpÂ®\n");
		res=1;
	}
	return res;
}

	/*Verifica se a invocacao ocorreu com argumentos de criacao de ficheiro*/
int verificaArgs_ArgumentosOut(int argc, char* argv[]){
	int res = 0;
	if (argc==2 || argc==4){
		res=1;
	}
	return res;
}
